//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddmlPack.API {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddmlPack.API.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append information from mets-file to addml-file.
        /// </summary>
        public static string AppendMetsInfo_Addml_Description {
            get {
                return ResourceManager.GetString("AppendMetsInfo_Addml_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append information from mets-file to excel-file.
        /// </summary>
        public static string AppendMetsInfo_Excel_Description {
            get {
                return ResourceManager.GetString("AppendMetsInfo_Excel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append defined processes to addml-file.
        /// </summary>
        public static string AppendProcesses_Addml_Description {
            get {
                return ResourceManager.GetString("AppendProcesses_Addml_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append defined processes to excel-file.
        /// </summary>
        public static string AppendProcesses_Excel_Description {
            get {
                return ResourceManager.GetString("AppendProcesses_Excel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the documentation of appendProcesses..
        /// </summary>
        public static string AppendProcesses_Help_Description {
            get {
                return ResourceManager.GetString("AppendProcesses_Help_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -co, --customoptions.
        /// </summary>
        public static string Arg_CustomOptions {
            get {
                return ResourceManager.GetString("Arg_CustomOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either a json-structure or filepath to json-file.
        /// </summary>
        public static string Arg_CustomOptions_Description {
            get {
                return ResourceManager.GetString("Arg_CustomOptions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -i, --input.
        /// </summary>
        public static string Arg_Input {
            get {
                return ResourceManager.GetString("Arg_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specify input filepath.
        /// </summary>
        public static string Arg_Input_Description {
            get {
                return ResourceManager.GetString("Arg_Input_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -l, --lang.
        /// </summary>
        public static string Arg_Language {
            get {
                return ResourceManager.GetString("Arg_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language used for excel-text..
        /// </summary>
        public static string Arg_Language_Description {
            get {
                return ResourceManager.GetString("Arg_Language_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -o, --output.
        /// </summary>
        public static string Arg_Output {
            get {
                return ResourceManager.GetString("Arg_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specify output filepath.
        /// </summary>
        public static string Arg_Output_Description {
            get {
                return ResourceManager.GetString("Arg_Output_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -t, --type.
        /// </summary>
        public static string Arg_Type {
            get {
                return ResourceManager.GetString("Arg_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subprocess, .
        /// </summary>
        public static string Arg_Type_Description {
            get {
                return ResourceManager.GetString("Arg_Type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     {0,-5} {1,-12} :{2}.
        /// </summary>
        public static string ArgShort_ArgLong_Description {
            get {
                return ResourceManager.GetString("ArgShort_ArgLong_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to convert addml-file to excel-file..
        /// </summary>
        public static string Convert_A2E_Description {
            get {
                return ResourceManager.GetString("Convert_A2E_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to convert excel-file to addml-file..
        /// </summary>
        public static string Convert_E2A_Description {
            get {
                return ResourceManager.GetString("Convert_E2A_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the documentation of convert..
        /// </summary>
        public static string Convert_Help_Description {
            get {
                return ResourceManager.GetString("Convert_Help_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generate addml-file from template included in library AddmlPack.Utils..
        /// </summary>
        public static string Generate_Addml_Description {
            get {
                return ResourceManager.GetString("Generate_Addml_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generate excel-file from template included in library AddmlPack.Utils..
        /// </summary>
        public static string Generate_Excel_Description {
            get {
                return ResourceManager.GetString("Generate_Excel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the documentation of generate..
        /// </summary>
        public static string Generate_Help_Description {
            get {
                return ResourceManager.GetString("Generate_Help_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid use of process, try help to list implemented processes and usage..
        /// </summary>
        public static string InvalidUseOfProcess {
            get {
                return ResourceManager.GetString("InvalidUseOfProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No process found, use help to list implemented processes and usage..
        /// </summary>
        public static string NoProcessFound {
            get {
                return ResourceManager.GetString("NoProcessFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-16} {1,-16} :{2}.
        /// </summary>
        public static string Process_Type_Description_Format {
            get {
                return ResourceManager.GetString("Process_Type_Description_Format", resourceCulture);
            }
        }
    }
}
