//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddmlPack.Standards.Addml {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Schema {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Schema() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddmlPack.Standards.Addml.Schema", typeof(Schema).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--    XML-DTD for                             --&gt;
        ///&lt;!--    ADDMML (Archives&apos; Data Description and Manipulation Markup Language):   --&gt;
        ///
        ///&lt;!--    Arkivverkets standard for teknisk og logisk beskrivelse og behandling   --&gt;
        ///&lt;!--    (sjekk, analyse og konvertering) av avlevert, digitalt arkivmateriale   --&gt;
        ///
        ///&lt;!ELEMENT addmml (reference, structure, processes?)&gt;
        ///&lt;!ATTLIST addmml
        ///            version CDATA #FIXED &quot;7.3&quot;&gt;
        ///&lt;!ELEMENT reference (archives, system)&gt;
        ///&lt;!ELEMENT archives (ar_name)&gt;
        ///&lt;!ATTLIST archi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string v7_3 {
            get {
                return ResourceManager.GetString("v7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;http://www.arkivverket.no/standarder/addml&quot;
        ///  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///  targetNamespace=&quot;http://www.arkivverket.no/standarder/addml&quot; elementFormDefault=&quot;qualified&quot; version=&quot;8.2&quot;&gt;
        ///  &lt;xs:element name=&quot;addml&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element ref=&quot;dataset&quot; maxOccurs=&quot;unbounded&quot;/&gt;
        ///      &lt;/xs:sequence&gt;
        ///      &lt;xs:attribute name=&quot;name&quot; type=&quot;xs:string&quot;/&gt;
        ///    &lt;/xs:complexType&gt;
        ///  &lt;/xs:e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string v8_2 {
            get {
                return ResourceManager.GetString("v8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;xs:schema xmlns:addml=&quot;http://www.arkivverket.no/standarder/addml&quot;
        ///  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///  targetNamespace=&quot;http://www.arkivverket.no/standarder/addml&quot; elementFormDefault=&quot;qualified&quot;
        ///  version=&quot;8.3&quot;&gt;
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation xml:lang=&quot;en&quot;&gt;
        ///      Changes made in versions up to 8.2 are not documented in this document.
        ///      Updated 2014-08-15 and 2014-09-29, Terje Pettersen-Dahl:
        ///      Version 8.3:
        ///      1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string v8_3 {
            get {
                return ResourceManager.GetString("v8_3", resourceCulture);
            }
        }
    }
}
