using System;
using System.Collections.Generic;
using System.Text;

namespace AddmlPack.Standards.Addml.Classes.v7_3
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.arkivverket.no/standarder/addml")]
    [System.Xml.Serialization.XmlRootAttribute("addmml", Namespace = "http://www.arkivverket.no/standarder/addml", IsNullable = false)]
    public partial class addmmlType
    {

        private referenceType referenceField;

        private structureType structureField;

        private processesType processesField;

        /// <remarks/>
        public referenceType reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }

        /// <remarks/>
        public structureType structure
        {
            get
            {
                return this.structureField;
            }
            set
            {
                this.structureField = value;
            }
        }

        /// <remarks/>
        public processesType processes
        {
            get
            {
                return this.processesField;
            }
            set
            {
                this.processesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.arkivverket.no/standarder/addml")]
    public partial class referenceType
    {

        private archivesType archivesField;

        private seriesType seriesField;

        private processesType processesField;

        /// <remarks/>
        public archivesType archives
        {
            get
            {
                return this.archivesField;
            }
            set
            {
                this.archivesField = value;
            }
        }

        /// <remarks/>
        public seriesType series
        {
            get
            {
                return this.seriesField;
            }
            set
            {
                this.seriesField = value;
            }
        }

        /// <remarks/>
        public processesType processes
        {
            get
            {
                return this.processesField;
            }
            set
            {
                this.processesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.arkivverket.no/standarder/addml")]
    public partial class archivesType
    {

        private string ar_nameField;

        private string ar_idField;

        /// <remarks/>
        public string ar_name
        {
            get
            {
                return this.ar_nameField;
            }
            set
            {
                this.ar_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ar_id
        {
            get
            {
                return this.ar_idField;
            }
            set
            {
                this.ar_idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.arkivverket.no/standarder/addml")]
    public partial class codeType
    {

        private string valueField;

        private string explanField;

        /// <remarks/>
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        public string explan
        {
            get
            {
                return this.explanField;
            }
            set
            {
                this.explanField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.arkivverket.no/standarder/addml")]
    public partial class fieldtypeType
    {

        private string ft_descrField;

        private string startposField;

        private string endposField;

        private string ft_fixlengthField;

        private string ft_minlengthField;

        private string ft_maxlengthField;

        private emtpyType repField;

        private string datatypeField;

        private string maskField;

        private string packedField;

        private string centuryField;

        private string ft_nullvalueField;

        private emtpyType nonullField;

        private emtpyType uniqueField;

        private codeType[] codeField;

        private string nameField;

        /// <remarks/>
        public string ft_descr
        {
            get
            {
                return this.ft_descrField;
            }
            set
            {
                this.ft_descrField = value;
            }
        }

        /// <remarks/>
        public string startpos
        {
            get
            {
                return this.startposField;
            }
            set
            {
                this.startposField = value;
            }
        }

        /// <remarks/>
        public string endpos
        {
            get
            {
                return this.endposField;
            }
            set
            {
                this.endposField = value;
            }
        }

        /// <remarks/>
        public string ft_fixlength
        {
            get
            {
                return this.ft_fixlengthField;
            }
            set
            {
                this.ft_fixlengthField = value;
            }
        }

        /// <remarks/>
        public string ft_minlength
        {
            get
            {
                return this.ft_minlengthField;
            }
            set
            {
                this.ft_minlengthField = value;
            }
        }

        /// <remarks/>
        public string ft_maxlength
        {
            get
            {
                return this.ft_maxlengthField;
            }
            set
            {
                this.ft_maxlengthField = value;
            }
        }

        /// <remarks/>
        public emtpyType rep
        {
            get
            {
                return this.repField;
            }
            set
            {
                this.repField = value;
            }
        }

        /// <remarks/>
        public string datatype
        {
            get
            {
                return this.datatypeField;
            }
            set
            {
                this.datatypeField = value;
            }
        }

        /// <remarks/>
        public string mask
        {
            get
            {
                return this.maskField;
            }
            set
            {
                this.maskField = value;
            }
        }

        /// <remarks/>
        public string packed
        {
            get
            {
                return this.packedField;
            }
            set
            {
                this.packedField = value;
            }
        }

        /// <remarks/>
        public string century
        {
            get
            {
                return this.centuryField;
            }
            set
            {
                this.centuryField = value;
            }
        }

        /// <remarks/>
        public string ft_nullvalue
        {
            get
            {
                return this.ft_nullvalueField;
            }
            set
            {
                this.ft_nullvalueField = value;
            }
        }

        /// <remarks/>
        public emtpyType nonull
        {
            get
            {
                return this.nonullField;
            }
            set
            {
                this.nonullField = value;
            }
        }

        /// <remarks/>
        public emtpyType unique
        {
            get
            {
                return this.uniqueField;
            }
            set
            {
                this.uniqueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("code")]
        public codeType[] code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.arkivverket.no/standarder/addml")]
    public partial class emtpyType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.arkivverket.no/standarder/addml")]
    public partial class forkeyType
    {

        private string fieldsField;

        private string reffilerecField;

        private string reffieldsField;

        private string reltypeField;

        /// <remarks/>
        public string fields
        {
            get
            {
                return this.fieldsField;
            }
            set
            {
                this.fieldsField = value;
            }
        }

        /// <remarks/>
        public string reffilerec
        {
            get
            {
                return this.reffilerecField;
            }
            set
            {
                this.reffilerecField = value;
            }
        }

        /// <remarks/>
        public string reffields
        {
            get
            {
                return this.reffieldsField;
            }
            set
            {
                this.reffieldsField = value;
            }
        }

        /// <remarks/>
        public string reltype
        {
            get
            {
                return this.reltypeField;
            }
            set
            {
                this.reltypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.arkivverket.no/standarder/addml")]
    public partial class rectypeType
    {

        private string rt_descrField;

        private string rt_idField;

        private string primkeyField;

        private string[] altkeyField;

        private forkeyType[] forkeyField;

        private string rt_fixlengthField;

        private string rt_minlengthField;

        private string rt_maxlengthField;

        private string nu_fieldsField;

        private string nu_recsField;

        private fieldtypeType[] fieldtypeField;

        private string nameField;

        /// <remarks/>
        public string rt_descr
        {
            get
            {
                return this.rt_descrField;
            }
            set
            {
                this.rt_descrField = value;
            }
        }

        /// <remarks/>
        public string rt_id
        {
            get
            {
                return this.rt_idField;
            }
            set
            {
                this.rt_idField = value;
            }
        }

        /// <remarks/>
        public string primkey
        {
            get
            {
                return this.primkeyField;
            }
            set
            {
                this.primkeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("altkey")]
        public string[] altkey
        {
            get
            {
                return this.altkeyField;
            }
            set
            {
                this.altkeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("forkey")]
        public forkeyType[] forkey
        {
            get
            {
                return this.forkeyField;
            }
            set
            {
                this.forkeyField = value;
            }
        }

        /// <remarks/>
        public string rt_fixlength
        {
            get
            {
                return this.rt_fixlengthField;
            }
            set
            {
                this.rt_fixlengthField = value;
            }
        }

        /// <remarks/>
        public string rt_minlength
        {
            get
            {
                return this.rt_minlengthField;
            }
            set
            {
                this.rt_minlengthField = value;
            }
        }

        /// <remarks/>
        public string rt_maxlength
        {
            get
            {
                return this.rt_maxlengthField;
            }
            set
            {
                this.rt_maxlengthField = value;
            }
        }

        /// <remarks/>
        public string nu_fields
        {
            get
            {
                return this.nu_fieldsField;
            }
            set
            {
                this.nu_fieldsField = value;
            }
        }

        /// <remarks/>
        public string nu_recs
        {
            get
            {
                return this.nu_recsField;
            }
            set
            {
                this.nu_recsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fieldtype")]
        public fieldtypeType[] fieldtype
        {
            get
            {
                return this.fieldtypeField;
            }
            set
            {
                this.fieldtypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.arkivverket.no/standarder/addml")]
    public partial class delimspecType
    {

        private string fieldsepField;

        private string quoteField;

        /// <remarks/>
        public string fieldsep
        {
            get
            {
                return this.fieldsepField;
            }
            set
            {
                this.fieldsepField = value;
            }
        }

        /// <remarks/>
        public string quote
        {
            get
            {
                return this.quoteField;
            }
            set
            {
                this.quoteField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.arkivverket.no/standarder/addml")]
    public partial class fileType
    {

        private string fi_descrField;

        private string recsepField;

        private string fi_formatField;

        private string reclengthField;

        private delimspecType delimspecField;

        private string padcharField;

        private string nu_rectypesField;

        private string rectypeidField;

        private string nu_recordsField;

        private string nu_bytesField;

        private rectypeType[] rectypeField;

        private string nameField;

        private string pathField;

        /// <remarks/>
        public string fi_descr
        {
            get
            {
                return this.fi_descrField;
            }
            set
            {
                this.fi_descrField = value;
            }
        }

        /// <remarks/>
        public string recsep
        {
            get
            {
                return this.recsepField;
            }
            set
            {
                this.recsepField = value;
            }
        }

        /// <remarks/>
        public string fi_format
        {
            get
            {
                return this.fi_formatField;
            }
            set
            {
                this.fi_formatField = value;
            }
        }

        /// <remarks/>
        public string reclength
        {
            get
            {
                return this.reclengthField;
            }
            set
            {
                this.reclengthField = value;
            }
        }

        /// <remarks/>
        public delimspecType delimspec
        {
            get
            {
                return this.delimspecField;
            }
            set
            {
                this.delimspecField = value;
            }
        }

        /// <remarks/>
        public string padchar
        {
            get
            {
                return this.padcharField;
            }
            set
            {
                this.padcharField = value;
            }
        }

        /// <remarks/>
        public string nu_rectypes
        {
            get
            {
                return this.nu_rectypesField;
            }
            set
            {
                this.nu_rectypesField = value;
            }
        }

        /// <remarks/>
        public string rectypeid
        {
            get
            {
                return this.rectypeidField;
            }
            set
            {
                this.rectypeidField = value;
            }
        }

        /// <remarks/>
        public string nu_records
        {
            get
            {
                return this.nu_recordsField;
            }
            set
            {
                this.nu_recordsField = value;
            }
        }

        /// <remarks/>
        public string nu_bytes
        {
            get
            {
                return this.nu_bytesField;
            }
            set
            {
                this.nu_bytesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rectype")]
        public rectypeType[] rectype
        {
            get
            {
                return this.rectypeField;
            }
            set
            {
                this.rectypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.arkivverket.no/standarder/addml")]
    public partial class sqlType
    {

        private string stnrField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stnr
        {
            get
            {
                return this.stnrField;
            }
            set
            {
                this.stnrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.arkivverket.no/standarder/addml")]
    public partial class chardefType
    {

        private string localField;

        private string isoField;

        /// <remarks/>
        public string local
        {
            get
            {
                return this.localField;
            }
            set
            {
                this.localField = value;
            }
        }

        /// <remarks/>
        public string iso
        {
            get
            {
                return this.isoField;
            }
            set
            {
                this.isoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.arkivverket.no/standarder/addml")]
    public partial class datasetType
    {

        private string ds_descrField;

        private string charsetField;

        private chardefType[] chardefField;

        private string formatField;

        private string string_nullField;

        private string integer_nullField;

        private string float_nullField;

        private string date_nullField;

        private string nu_filesField;

        private sqlType[] sqlField;

        private fileType[] fileField;

        private string ds_idField;

        /// <remarks/>
        public string ds_descr
        {
            get
            {
                return this.ds_descrField;
            }
            set
            {
                this.ds_descrField = value;
            }
        }

        /// <remarks/>
        public string charset
        {
            get
            {
                return this.charsetField;
            }
            set
            {
                this.charsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("chardef")]
        public chardefType[] chardef
        {
            get
            {
                return this.chardefField;
            }
            set
            {
                this.chardefField = value;
            }
        }

        /// <remarks/>
        public string format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }

        /// <remarks/>
        public string string_null
        {
            get
            {
                return this.string_nullField;
            }
            set
            {
                this.string_nullField = value;
            }
        }

        /// <remarks/>
        public string integer_null
        {
            get
            {
                return this.integer_nullField;
            }
            set
            {
                this.integer_nullField = value;
            }
        }

        /// <remarks/>
        public string float_null
        {
            get
            {
                return this.float_nullField;
            }
            set
            {
                this.float_nullField = value;
            }
        }

        /// <remarks/>
        public string date_null
        {
            get
            {
                return this.date_nullField;
            }
            set
            {
                this.date_nullField = value;
            }
        }

        /// <remarks/>
        public string nu_files
        {
            get
            {
                return this.nu_filesField;
            }
            set
            {
                this.nu_filesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sql")]
        public sqlType[] sql
        {
            get
            {
                return this.sqlField;
            }
            set
            {
                this.sqlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("file")]
        public fileType[] file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ds_id
        {
            get
            {
                return this.ds_idField;
            }
            set
            {
                this.ds_idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.arkivverket.no/standarder/addml")]
    public partial class structureType
    {

        private datasetType datasetField;

        /// <remarks/>
        public datasetType dataset
        {
            get
            {
                return this.datasetField;
            }
            set
            {
                this.datasetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.arkivverket.no/standarder/addml")]
    public partial class p_fieldtypeType
    {

        private string[] ft_checkField;

        private emtpyType ft_analysisField;

        private emtpyType freqField;

        private emtpyType unpackField;

        private string new_datatypeField;

        private string new_maskField;

        private string fileField;

        private string rectypeField;

        private string fieldtypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ft_check")]
        public string[] ft_check
        {
            get
            {
                return this.ft_checkField;
            }
            set
            {
                this.ft_checkField = value;
            }
        }

        /// <remarks/>
        public emtpyType ft_analysis
        {
            get
            {
                return this.ft_analysisField;
            }
            set
            {
                this.ft_analysisField = value;
            }
        }

        /// <remarks/>
        public emtpyType freq
        {
            get
            {
                return this.freqField;
            }
            set
            {
                this.freqField = value;
            }
        }

        /// <remarks/>
        public emtpyType unpack
        {
            get
            {
                return this.unpackField;
            }
            set
            {
                this.unpackField = value;
            }
        }

        /// <remarks/>
        public string new_datatype
        {
            get
            {
                return this.new_datatypeField;
            }
            set
            {
                this.new_datatypeField = value;
            }
        }

        /// <remarks/>
        public string new_mask
        {
            get
            {
                return this.new_maskField;
            }
            set
            {
                this.new_maskField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rectype
        {
            get
            {
                return this.rectypeField;
            }
            set
            {
                this.rectypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fieldtype
        {
            get
            {
                return this.fieldtypeField;
            }
            set
            {
                this.fieldtypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.arkivverket.no/standarder/addml")]
    public partial class p_rectypeType
    {

        private string[] rt_checkField;

        private string rt_analysisField;

        private emtpyType freq_allfieldsField;

        private string[] crosstabField;

        private string extractField;

        private emtpyType split_repgroupsField;

        private string fileField;

        private string rectypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rt_check")]
        public string[] rt_check
        {
            get
            {
                return this.rt_checkField;
            }
            set
            {
                this.rt_checkField = value;
            }
        }

        /// <remarks/>
        public string rt_analysis
        {
            get
            {
                return this.rt_analysisField;
            }
            set
            {
                this.rt_analysisField = value;
            }
        }

        /// <remarks/>
        public emtpyType freq_allfields
        {
            get
            {
                return this.freq_allfieldsField;
            }
            set
            {
                this.freq_allfieldsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("crosstab")]
        public string[] crosstab
        {
            get
            {
                return this.crosstabField;
            }
            set
            {
                this.crosstabField = value;
            }
        }

        /// <remarks/>
        public string extract
        {
            get
            {
                return this.extractField;
            }
            set
            {
                this.extractField = value;
            }
        }

        /// <remarks/>
        public emtpyType split_repgroups
        {
            get
            {
                return this.split_repgroupsField;
            }
            set
            {
                this.split_repgroupsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rectype
        {
            get
            {
                return this.rectypeField;
            }
            set
            {
                this.rectypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.arkivverket.no/standarder/addml")]
    public partial class p_fileType
    {

        private string[] fi_checkField;

        private string fi_analysisField;

        private string new_recsepField;

        private string fi_new_formatField;

        private string extractField;

        private emtpyType split_rectypesField;

        private string fileField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fi_check")]
        public string[] fi_check
        {
            get
            {
                return this.fi_checkField;
            }
            set
            {
                this.fi_checkField = value;
            }
        }

        /// <remarks/>
        public string fi_analysis
        {
            get
            {
                return this.fi_analysisField;
            }
            set
            {
                this.fi_analysisField = value;
            }
        }

        /// <remarks/>
        public string new_recsep
        {
            get
            {
                return this.new_recsepField;
            }
            set
            {
                this.new_recsepField = value;
            }
        }

        /// <remarks/>
        public string fi_new_format
        {
            get
            {
                return this.fi_new_formatField;
            }
            set
            {
                this.fi_new_formatField = value;
            }
        }

        /// <remarks/>
        public string extract
        {
            get
            {
                return this.extractField;
            }
            set
            {
                this.extractField = value;
            }
        }

        /// <remarks/>
        public emtpyType split_rectypes
        {
            get
            {
                return this.split_rectypesField;
            }
            set
            {
                this.split_rectypesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.arkivverket.no/standarder/addml")]
    public partial class p_datasetType
    {

        private string ds_analysisField;

        private string new_charsetField;

        private string new_formatField;

        /// <remarks/>
        public string ds_analysis
        {
            get
            {
                return this.ds_analysisField;
            }
            set
            {
                this.ds_analysisField = value;
            }
        }

        /// <remarks/>
        public string new_charset
        {
            get
            {
                return this.new_charsetField;
            }
            set
            {
                this.new_charsetField = value;
            }
        }

        /// <remarks/>
        public string new_format
        {
            get
            {
                return this.new_formatField;
            }
            set
            {
                this.new_formatField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.arkivverket.no/standarder/addml")]
    public partial class processesType
    {

        private object[] itemsField;

        private string spcField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("p_dataset", typeof(p_datasetType))]
        [System.Xml.Serialization.XmlElementAttribute("p_fieldtype", typeof(p_fieldtypeType))]
        [System.Xml.Serialization.XmlElementAttribute("p_file", typeof(p_fileType))]
        [System.Xml.Serialization.XmlElementAttribute("p_rectype", typeof(p_rectypeType))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string spc
        {
            get
            {
                return this.spcField;
            }
            set
            {
                this.spcField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.arkivverket.no/standarder/addml")]
    public partial class seriesType
    {

        private string se_nameField;

        private string startdateField;

        private string enddateField;

        private string se_idField;

        /// <remarks/>
        public string se_name
        {
            get
            {
                return this.se_nameField;
            }
            set
            {
                this.se_nameField = value;
            }
        }

        /// <remarks/>
        public string startdate
        {
            get
            {
                return this.startdateField;
            }
            set
            {
                this.startdateField = value;
            }
        }

        /// <remarks/>
        public string enddate
        {
            get
            {
                return this.enddateField;
            }
            set
            {
                this.enddateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string se_id
        {
            get
            {
                return this.se_idField;
            }
            set
            {
                this.se_idField = value;
            }
        }
    }
}