//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddmlPack.Utils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddmlPack.Utils.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;addml xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://www.arkivverket.no/standarder/addml addml.xsd&quot; xmlns=&quot;http://www.arkivverket.no/standarder/addml&quot; name=&quot;Arkivnavn&quot;&gt;
        ///  &lt;dataset name=&quot;Filarkiv&quot;&gt;
        ///    &lt;description&gt;Arkivmateriale.&lt;/description&gt;
        ///    &lt;reference /&gt;
        ///    &lt;flatFiles&gt;
        ///      &lt;flatFile definitionReference=&quot;FilarkivDef&quot; name=&quot;Filarkiv-analyse&quot;&gt;
        ///        &lt;properties&gt;
        ///          &lt;property name=&quot;fileName&quot;&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Addml_for_FF {
            get {
                return ResourceManager.GetString("Addml_for_FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;addml xmlns=&quot;http://www.arkivverket.no/standarder/addml&quot;
        ///   xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///   name=&quot;Mal for arkivuttrekk som følger Noark 3&quot;
        ///   xsi:schemaLocation=&quot;http://www.arkivverket.no/standarder/addml addml.xsd&quot;&gt;
        ///   &lt;dataset name=&quot;Noark_3&quot;&gt;
        ///      &lt;reference&gt;
        ///         &lt;context&gt;
        ///            &lt;additionalElements&gt;
        ///               &lt;additionalElement name=&quot;systemType&quot;&gt;
        ///                  &lt;value&gt;Journalsystem (Noark-3)&lt;/value&gt;
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Addml_for_N3 {
            get {
                return ResourceManager.GetString("Addml_for_N3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;addml xmlns=&quot;http://www.arkivverket.no/standarder/addml&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://www.arkivverket.no/standarder/addml addml.xsd&quot; name=&quot;Noark 5-arkivuttrekk&quot;&gt;
        ///  &lt;dataset&gt;
        ///    &lt;description&gt;Noark 5-arkivuttrekk&lt;/description&gt;
        ///    &lt;reference&gt;
        ///      &lt;context&gt;
        ///        &lt;additionalElements&gt;
        ///          &lt;additionalElement name=&quot;recordCreators&quot;&gt;
        ///            &lt;additionalElements&gt;
        ///              &lt;additionalElement name=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Addml_for_N5 {
            get {
                return ResourceManager.GetString("Addml_for_N5", resourceCulture);
            }
        }
    }
}
