//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddmlPack.Utils.Spreadsheet.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Excel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Excel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddmlPack.Utils.Spreadsheet.Languages.Excel", typeof(Excel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactinformation.
        /// </summary>
        internal static string Agent_Contact {
            get {
                return ResourceManager.GetString("Agent_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of contact information.
        /// </summary>
        internal static string Agent_ContactType {
            get {
                return ResourceManager.GetString("Agent_ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Subject To.
        /// </summary>
        internal static string Agent_IsSubjectTo {
            get {
                return ResourceManager.GetString("Agent_IsSubjectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Agent_Role {
            get {
                return ResourceManager.GetString("Agent_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of agent.
        /// </summary>
        internal static string Agent_Type {
            get {
                return ResourceManager.GetString("Agent_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From character.
        /// </summary>
        internal static string CharacterDefinitions_FromCharacter {
            get {
                return ResourceManager.GetString("CharacterDefinitions_FromCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To character.
        /// </summary>
        internal static string CharacterDefinitions_ToCharacter {
            get {
                return ResourceManager.GetString("CharacterDefinitions_ToCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation.
        /// </summary>
        internal static string Code_Explanation {
            get {
                return ResourceManager.GetString("Code_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Code_Value {
            get {
                return ResourceManager.GetString("Code_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentaries.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataObjects.
        /// </summary>
        internal static string DataObjects {
            get {
                return ResourceManager.GetString("DataObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are codes defines?.
        /// </summary>
        internal static string Field_Definition_Codes {
            get {
                return ResourceManager.GetString("Field_Definition_Codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End-position of field.
        /// </summary>
        internal static string Field_Definition_EndPos {
            get {
                return ResourceManager.GetString("Field_Definition_EndPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are fields nested?.
        /// </summary>
        internal static string Field_Definition_Fieldparts {
            get {
                return ResourceManager.GetString("Field_Definition_Fieldparts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed length of field.
        /// </summary>
        internal static string Field_Definition_FixedLength {
            get {
                return ResourceManager.GetString("Field_Definition_FixedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length of field.
        /// </summary>
        internal static string Field_Definition_MaxLength {
            get {
                return ResourceManager.GetString("Field_Definition_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length of field.
        /// </summary>
        internal static string Field_Definition_MinLength {
            get {
                return ResourceManager.GetString("Field_Definition_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are empty fields allowed?.
        /// </summary>
        internal static string Field_Definition_NotNull {
            get {
                return ResourceManager.GetString("Field_Definition_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has process.
        /// </summary>
        internal static string Field_Definition_Process {
            get {
                return ResourceManager.GetString("Field_Definition_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to field-definition.
        /// </summary>
        internal static string Field_Definition_Reference {
            get {
                return ResourceManager.GetString("Field_Definition_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start-position of field.
        /// </summary>
        internal static string Field_Definition_StartPos {
            get {
                return ResourceManager.GetString("Field_Definition_StartPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are field-vaues unique.
        /// </summary>
        internal static string Field_Definition_Unique {
            get {
                return ResourceManager.GetString("Field_Definition_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field-processes.
        /// </summary>
        internal static string Field_Processes {
            get {
                return ResourceManager.GetString("Field_Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment of value inside field.
        /// </summary>
        internal static string Field_Type_Alignment {
            get {
                return ResourceManager.GetString("Field_Type_Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data-type of field.
        /// </summary>
        internal static string Field_Type_Datatype {
            get {
                return ResourceManager.GetString("Field_Type_Datatype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format of fieldvalue.
        /// </summary>
        internal static string Field_Type_FieldFormat {
            get {
                return ResourceManager.GetString("Field_Type_FieldFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null-values.
        /// </summary>
        internal static string Field_Type_NullValues {
            get {
                return ResourceManager.GetString("Field_Type_NullValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If field is packed or packing-algorithm.
        /// </summary>
        internal static string Field_Type_Packing {
            get {
                return ResourceManager.GetString("Field_Type_Packing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters used for padding.
        /// </summary>
        internal static string Field_Type_Padding {
            get {
                return ResourceManager.GetString("Field_Type_Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum-algorithm.
        /// </summary>
        internal static string File_ChecksumAlgorithm {
            get {
                return ResourceManager.GetString("File_ChecksumAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum-value.
        /// </summary>
        internal static string File_ChecksumValue {
            get {
                return ResourceManager.GetString("File_ChecksumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to file-definition.
        /// </summary>
        internal static string File_Definition_Reference {
            get {
                return ResourceManager.GetString("File_Definition_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of records in file.
        /// </summary>
        internal static string File_NumberOfRecords {
            get {
                return ResourceManager.GetString("File_NumberOfRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has process.
        /// </summary>
        internal static string File_Process {
            get {
                return ResourceManager.GetString("File_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File-processes.
        /// </summary>
        internal static string File_Processes {
            get {
                return ResourceManager.GetString("File_Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to file.
        /// </summary>
        internal static string File_Reference {
            get {
                return ResourceManager.GetString("File_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative filepath.
        /// </summary>
        internal static string File_Relative_Path {
            get {
                return ResourceManager.GetString("File_Relative_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are character-definitions in use?.
        /// </summary>
        internal static string File_Type_CharacterDefinitions {
            get {
                return ResourceManager.GetString("File_Type_CharacterDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charset.
        /// </summary>
        internal static string File_Type_Charset {
            get {
                return ResourceManager.GetString("File_Type_Charset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field-separator.
        /// </summary>
        internal static string File_Type_FieldSeparator {
            get {
                return ResourceManager.GetString("File_Type_FieldSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed-length or Delimited.
        /// </summary>
        internal static string File_Type_FixedOrDelimited {
            get {
                return ResourceManager.GetString("File_Type_FixedOrDelimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimited.
        /// </summary>
        internal static string File_Type_FixedOrDelimited_Delimited {
            get {
                return ResourceManager.GetString("File_Type_FixedOrDelimited_Delimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed-length.
        /// </summary>
        internal static string File_Type_FixedOrDelimited_Fixed {
            get {
                return ResourceManager.GetString("File_Type_FixedOrDelimited_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation-character.
        /// </summary>
        internal static string File_Type_QuotationSeparator {
            get {
                return ResourceManager.GetString("File_Type_QuotationSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record-separator.
        /// </summary>
        internal static string File_Type_RecordSeparator {
            get {
                return ResourceManager.GetString("File_Type_RecordSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File-type reference.
        /// </summary>
        internal static string File_Type_Reference {
            get {
                return ResourceManager.GetString("File_Type_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in dataset.
        /// </summary>
        internal static string InDataset {
            get {
                return ResourceManager.GetString("InDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary or Alternate Key.
        /// </summary>
        internal static string Key_PrimaryOrAlternate {
            get {
                return ResourceManager.GetString("Key_PrimaryOrAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys.
        /// </summary>
        internal static string Keys {
            get {
                return ResourceManager.GetString("Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Key.
        /// </summary>
        internal static string Keys_AlternateKey {
            get {
                return ResourceManager.GetString("Keys_AlternateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Key.
        /// </summary>
        internal static string Keys_ForeignKey {
            get {
                return ResourceManager.GetString("Keys_ForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Key.
        /// </summary>
        internal static string Keys_PrimaryKey {
            get {
                return ResourceManager.GetString("Keys_PrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation between two sets of referenced field(s).
        /// </summary>
        internal static string Keys_Relation {
            get {
                return ResourceManager.GetString("Keys_Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of {0} in use: {1}.
        /// </summary>
        internal static string NumberInUse {
            get {
                return ResourceManager.GetString("NumberInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains company-specific metadata.
        /// </summary>
        internal static string Object_Archive_ContainsCompanySpecificMetadata {
            get {
                return ResourceManager.GetString("Object_Archive_ContainsCompanySpecificMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains disposal resolutions for documents.
        /// </summary>
        internal static string Object_Archive_ContainsDisposalResolutionsForDocuments {
            get {
                return ResourceManager.GetString("Object_Archive_ContainsDisposalResolutionsForDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains restricted entries.
        /// </summary>
        internal static string Object_Archive_ContainsRestrictedEntries {
            get {
                return ResourceManager.GetString("Object_Archive_ContainsRestrictedEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes disposed documents.
        /// </summary>
        internal static string Object_Archive_IncludeDisposedDocuments {
            get {
                return ResourceManager.GetString("Object_Archive_IncludeDisposedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of documents.
        /// </summary>
        internal static string Object_Archive_NumberOfDocuments {
            get {
                return ResourceManager.GetString("Object_Archive_NumberOfDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingoing separator for period.
        /// </summary>
        internal static string Object_Archive_Period_IngoingSeparation {
            get {
                return ResourceManager.GetString("Object_Archive_Period_IngoingSeparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing separator for period.
        /// </summary>
        internal static string Object_Archive_Period_OutgoingSeparation {
            get {
                return ResourceManager.GetString("Object_Archive_Period_OutgoingSeparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of archive.
        /// </summary>
        internal static string Object_Archive_Type {
            get {
                return ResourceManager.GetString("Object_Archive_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Object_Archive_TypeVersion {
            get {
                return ResourceManager.GetString("Object_Archive_TypeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        internal static string Object_Parent {
            get {
                return ResourceManager.GetString("Object_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of DataObject.
        /// </summary>
        internal static string Object_Type {
            get {
                return ResourceManager.GetString("Object_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Object_TypeVersion {
            get {
                return ResourceManager.GetString("Object_TypeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        internal static string Objects {
            get {
                return ResourceManager.GetString("Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fieldvalue identifying record-definition.
        /// </summary>
        internal static string Record_Definition_FieldValue {
            get {
                return ResourceManager.GetString("Record_Definition_FieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed length.
        /// </summary>
        internal static string Record_Definition_FixedLength {
            get {
                return ResourceManager.GetString("Record_Definition_FixedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is incomplete?.
        /// </summary>
        internal static string Record_Definition_Incomplete {
            get {
                return ResourceManager.GetString("Record_Definition_Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses keys?.
        /// </summary>
        internal static string Record_Definition_Keys {
            get {
                return ResourceManager.GetString("Record_Definition_Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has process?.
        /// </summary>
        internal static string Record_Definition_Process {
            get {
                return ResourceManager.GetString("Record_Definition_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to record-definition.
        /// </summary>
        internal static string Record_Definition_Reference {
            get {
                return ResourceManager.GetString("Record_Definition_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses repeating groups.
        /// </summary>
        internal static string Record_Definition_RepeatingGroups {
            get {
                return ResourceManager.GetString("Record_Definition_RepeatingGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record-processes.
        /// </summary>
        internal static string Record_Processes {
            get {
                return ResourceManager.GetString("Record_Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is record trimmed?.
        /// </summary>
        internal static string Record_Type_Trimming {
            get {
                return ResourceManager.GetString("Record_Type_Trimming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End-date of archival period.
        /// </summary>
        internal static string Reference_ArchivalPeriod_End {
            get {
                return ResourceManager.GetString("Reference_ArchivalPeriod_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start-date of archival period.
        /// </summary>
        internal static string Reference_ArchivalPeriod_Start {
            get {
                return ResourceManager.GetString("Reference_ArchivalPeriod_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of archive.
        /// </summary>
        internal static string Reference_Archive {
            get {
                return ResourceManager.GetString("Reference_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of system.
        /// </summary>
        internal static string Reference_System_Name {
            get {
                return ResourceManager.GetString("Reference_System_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of system.
        /// </summary>
        internal static string Reference_System_Type {
            get {
                return ResourceManager.GetString("Reference_System_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agents.
        /// </summary>
        internal static string Section_Agents {
            get {
                return ResourceManager.GetString("Section_Agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate keys.
        /// </summary>
        internal static string Section_CandidateKeys {
            get {
                return ResourceManager.GetString("Section_CandidateKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character-definitions.
        /// </summary>
        internal static string Section_CharacterDefinitions {
            get {
                return ResourceManager.GetString("Section_CharacterDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codes.
        /// </summary>
        internal static string Section_Codes {
            get {
                return ResourceManager.GetString("Section_Codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field-definitions.
        /// </summary>
        internal static string Section_Field_Definitions {
            get {
                return ResourceManager.GetString("Section_Field_Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field-types.
        /// </summary>
        internal static string Section_Field_Types {
            get {
                return ResourceManager.GetString("Section_Field_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string Section_File {
            get {
                return ResourceManager.GetString("Section_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File-definitions.
        /// </summary>
        internal static string Section_File_Definitions {
            get {
                return ResourceManager.GetString("Section_File_Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File-types.
        /// </summary>
        internal static string Section_File_Types {
            get {
                return ResourceManager.GetString("Section_File_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Keys.
        /// </summary>
        internal static string Section_ForeignKeys {
            get {
                return ResourceManager.GetString("Section_ForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive-level.
        /// </summary>
        internal static string Section_Object_Archive {
            get {
                return ResourceManager.GetString("Section_Object_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object-structure.
        /// </summary>
        internal static string Section_Object_Structure {
            get {
                return ResourceManager.GetString("Section_Object_Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File-info.
        /// </summary>
        internal static string Section_Object_Xml_File {
            get {
                return ResourceManager.GetString("Section_Object_Xml_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info regarding number of occurrences.
        /// </summary>
        internal static string Section_Object_Xml_NumberOfOccurrences {
            get {
                return ResourceManager.GetString("Section_Object_Xml_NumberOfOccurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema-info.
        /// </summary>
        internal static string Section_Object_Xml_Schema {
            get {
                return ResourceManager.GetString("Section_Object_Xml_Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        internal static string Section_Objects {
            get {
                return ResourceManager.GetString("Section_Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate keys.
        /// </summary>
        internal static string Section_PrimaryKeys {
            get {
                return ResourceManager.GetString("Section_PrimaryKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosesses.
        /// </summary>
        internal static string Section_Processes {
            get {
                return ResourceManager.GetString("Section_Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record-definitions.
        /// </summary>
        internal static string Section_Record_Definitions {
            get {
                return ResourceManager.GetString("Section_Record_Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record-types.
        /// </summary>
        internal static string Section_Record_Types {
            get {
                return ResourceManager.GetString("Section_Record_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset.
        /// </summary>
        internal static string Sheet_Dataset {
            get {
                return ResourceManager.GetString("Sheet_Dataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        internal static string Sheet_Definitions {
            get {
                return ResourceManager.GetString("Sheet_Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Files.
        /// </summary>
        internal static string Sheet_FlatFiles {
            get {
                return ResourceManager.GetString("Sheet_FlatFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Files Other Options.
        /// </summary>
        internal static string Sheet_FlatFiles_OtherOptions {
            get {
                return ResourceManager.GetString("Sheet_FlatFiles_OtherOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys.
        /// </summary>
        internal static string Sheet_Keys {
            get {
                return ResourceManager.GetString("Sheet_Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        internal static string Sheet_Objects {
            get {
                return ResourceManager.GetString("Sheet_Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object-structure.
        /// </summary>
        internal static string Sheet_Objects_Structure {
            get {
                return ResourceManager.GetString("Sheet_Objects_Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects - XML.
        /// </summary>
        internal static string Sheet_Objects_XML {
            get {
                return ResourceManager.GetString("Sheet_Objects_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        internal static string Sheet_Processes {
            get {
                return ResourceManager.GetString("Sheet_Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        internal static string Sheet_Types {
            get {
                return ResourceManager.GetString("Sheet_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string System_History {
            get {
                return ResourceManager.GetString("System_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of system.
        /// </summary>
        internal static string System_Name {
            get {
                return ResourceManager.GetString("System_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of system.
        /// </summary>
        internal static string System_SystemType {
            get {
                return ResourceManager.GetString("System_SystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string System_Version {
            get {
                return ResourceManager.GetString("System_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to type.
        /// </summary>
        internal static string Type_Reference {
            get {
                return ResourceManager.GetString("Type_Reference", resourceCulture);
            }
        }
    }
}
